### ISSUE TITLE
Failed installation: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats'

### ISSUE THREAD

**Issue by kdorman** [didillysquat/SymPortal_framework#125]
After following the instructions here: https://github.com/didillysquat/SymPortal_framework/wiki/0_3_18_19_SymPortal-setup, step 6 Check your installation fails with (I have replaced my working directory with $HOME in the following traceback):

$ python3 -m tests.tests
Traceback (most recent call last):
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "$HOME/SymPortal_framework/tests/tests.py", line 3, in <module>
    import main
  File "$HOME/SymPortal_framework/main.py", line 42, in <module>
    import distance
  File "$HOME/SymPortal_framework/distance.py", line 10, in <module>
    from skbio.diversity import beta_diversity
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/site-packages/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/site-packages/skbio/io/__init__.py", line 247, in <module>
    import_module('skbio.io.format.lsmat')
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/site-packages/skbio/io/format/lsmat.py", line 77, in <module>
    from skbio.stats.distance import DissimilarityMatrix, DistanceMatrix
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/site-packages/skbio/stats/distance/__init__.py", line 197, in <module>
    from ._mantel import mantel, pwmantel
  File "$HOME/.conda/envs/symportal_env/lib/python3.8/site-packages/skbio/stats/distance/_mantel.py", line 16, in <module>
    from scipy.stats import PearsonRConstantInputWarning
ImportError: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats' ($HOME/.conda/envs/symportal_env/lib/python3.8/site-packages/scipy/stats/__init__.py)

**Comment by didillysquat** [comment]
Hi @kdorman,

Thanks for pointing out this issue. It was caused due to scipy having removed some functionality from recent versions.

I've downgraded the requirements in the *.yml file to fix this.

If you reinstall the conda env using the updated yml or downgrade to the following in your current env:
scipy==1.5.3
scikit-bio==0.5.6

the import error should be fixed.

All the best,

Ben
