### ISSUE TITLE
Local install breaks with both SQLite and PostgreSQL

### ISSUE THREAD

**Issue by Nicholas-Kron** [didillysquat/SymPortal_framework#129]
Hi there,

I am attempting to set up a local install but so far I cannot get past the initial test. I'm on a Linux machine with Pop!_OS 22.04 LTS and Linux kernal 6.0.6-76060006-generic.

I followed the instructions outlined on the [wiki](https://github.com/didillysquat/SymPortal_framework/wiki/0_3_18_19_SymPortal-setup) . 

I followed the provided [example](https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04#configure-the-django-database-settings) for setting up PostgressSQL, but when attempting to get PostgresSQL to work, the `manage.py migrate` step throws the difficult to debug `There was an error loading django modules. Do you have django installed?` error. All requisite packages are installed and functioning, and the psql db exists. Updating numpy as I saw in [issue #75 ] did not fix this error. 

I tried proceeding with SQLite instead, and I manage to get the reference sequences loaded into the DB, but during the install test I get the following error:

```
Data loading complete. DataSet UID: 1; Name: testing

Generating count tables for post- and pre-MED sequence abundances


Outputting sequence abundance count tables

no_sym_1: collecting seq abundancesdances

Outputting seq data
Outputting seq data for Y13: sequence C3dd_CC
Generating ordered sample list and ordering dataframe accordingly
43: Getting maj seq for sample
Going clade by clade sorting by abundance
Populating the relative dataframe with series. This could take a while...
Generating accession and fasta
Appending accession info and creating fasta C3dd: 84/85Traceback (most recent call last): 15/8585
  File "/home/nicholaskron/miniconda3/envs/symportal_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nicholaskron/miniconda3/envs/symportal_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/tests/tests.py", line 154, in <module>
    symportal_tester.execute_integrated_tests()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/tests/tests.py", line 24, in execute_integrated_tests
    self._test_data_loading_work_flow()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/tests/tests.py", line 32, in _test_data_loading_work_flow
    self.work_flow_manager.start_work_flow()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/main.py", line 329, in start_work_flow
    self.perform_data_loading()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/main.py", line 695, in perform_data_loading
    self._execute_data_loading()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/main.py", line 722, in _execute_data_loading
    self.data_loading_object.load_data()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/data_loading.py", line 213, in load_data
    self._output_seqs_count_table()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/data_loading.py", line 363, in _output_seqs_count_table
    self.sequence_count_table_creator.make_seq_output_tables()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/output.py", line 1092, in make_seq_output_tables
    self._make_output_tables_post_med()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/output.py", line 1111, in _make_output_tables_post_med
    self._add_uids_for_seqs_to_dfs()
  File "/home/nicholaskron/Programs/local/SymPortal_framework-0.3.24/output.py", line 1498, in _add_uids_for_seqs_to_dfs
    self.output_df_absolute_post_med = self.output_df_absolute_post_med.append(temp_series)
  File "/home/nicholaskron/miniconda3/envs/symportal_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

Is this maybe a pandas version compatibility issue?

Here is the conda env I have:
```
# packages in environment at /home/nicholaskron/miniconda3/envs/symportal_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asgiref                   3.7.2              pyhd8ed1ab_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1            py38h0a891b7_7    conda-forge
bcrypt                    3.2.2            py38h0a891b7_1    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
biopython                 1.81             py38h1de0b5d_0    conda-forge
blast                     2.14.0          pl5321h6f7f691_2    bioconda
blast-legacy              2.2.26               h9ee0642_3    bioconda
boost                     1.70.0           py38h9de70de_1    conda-forge
boost-cpp                 1.70.0               ha2d47e9_1    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9            py38hfa26641_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachecontrol              0.13.1             pyhd8ed1ab_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0            py38h7f3f72f_0    conda-forge
cryptography              41.0.3           py38hcdda232_0    conda-forge
curl                      8.1.2                h409715c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    3.0.0            py38h17151c0_0    conda-forge
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
django                    4.2.3              pyhd8ed1ab_0    conda-forge
entrez-direct             16.2                 he881be0_1    bioconda
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.42.0           py38h01eb140_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gst-plugins-base          1.14.0               h8213a91_2    anaconda
gstreamer                 1.14.0               h28cd5cc_2    anaconda
hdf5                      1.10.5          nompi_h5b725eb_1114    conda-forge
hdmedians                 0.14.2           py38h26c90d9_3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-resources       6.0.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipython                   8.12.2             pyh41d4057_0    conda-forge
iqtree                    2.2.3                h21ec9f0_0    bioconda
jedi                      0.19.0             pyhd8ed1ab_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py38h43d8883_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  10.0.1          default_hde54327_1    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     12.15                hdbd6064_1  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.14               h74e7548_0    anaconda
libzlib                   1.2.13               hd590300_5    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
mafft                     7.520                h031d066_2    bioconda
markupsafe                2.1.3            py38h01eb140_0    conda-forge
matplotlib                3.7.2            py38h578d9bd_0    conda-forge
matplotlib-base           3.7.2            py38hf5b0b65_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mothur                    1.43.0               hd76352b_0    bioconda
msgpack-python            1.0.5            py38hfbd4bf9_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
ncbi-vdb                  3.0.6                hdbdd923_0    bioconda
ncurses                   6.4                  hcb278e6_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.89                 he45b914_0    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openpyxl                  3.1.2            py38h01eb140_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3            py38h01efb38_1    conda-forge
paramiko                  3.3.1              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
perl-alien-build          2.48            pl5321hec16e2b_0    bioconda
perl-alien-libxml2        0.17            pl5321hec16e2b_0    bioconda
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-business-isbn        3.007           pl5321hd8ed1ab_0    conda-forge
perl-business-isbn-data   20210112.006    pl5321hd8ed1ab_0    conda-forge
perl-capture-tiny         0.48            pl5321ha770c72_1    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-constant             1.33            pl5321hd8ed1ab_0    conda-forge
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-ffi-checklib         0.28            pl5321hdfd78af_0    bioconda
perl-file-chdir           0.1011          pl5321hd8ed1ab_0    conda-forge
perl-file-path            2.18            pl5321hd8ed1ab_0    conda-forge
perl-file-temp            0.2304          pl5321hd8ed1ab_0    conda-forge
perl-file-which           1.24            pl5321hd8ed1ab_0    conda-forge
perl-importer             0.026           pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-path-tiny            0.124           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-scope-guard          0.21            pl5321hd8ed1ab_0    conda-forge
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-sub-info             0.002           pl5321hd8ed1ab_0    conda-forge
perl-term-table           0.016           pl5321hdfd78af_0    bioconda
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-test-warnings        0.031           pl5321ha770c72_0    conda-forge
perl-test2-suite          0.000145        pl5321hdfd78af_0    bioconda
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-uri                  5.17            pl5321ha770c72_0    conda-forge
perl-xml-libxml           2.0207          pl5321h661654b_0    bioconda
perl-xml-namespacesupport 1.12            pl5321hd8ed1ab_0    conda-forge
perl-xml-sax              1.02            pl5321hd8ed1ab_0    conda-forge
perl-xml-sax-base         1.09            pl5321hd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h8e6f84c_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
plumbum                   1.8.2              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psycopg2                  2.9.3            py38h37d81fd_0    anaconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py38h0a891b7_2    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.4           py38hfa26641_0    conda-forge
pyqt5-sip                 12.9.0           py38hfa26641_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.0              pyhd8ed1ab_0    conda-forge
python                    3.8.17          he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywin32-on-windows        0.1.0              pyh1179c8e_3    conda-forge
qt-main                   5.15.2               h327a75a_7    anaconda
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scikit-bio                0.5.6            py38h0b5ebd8_4    conda-forge
scikit-learn              1.3.0            py38hc099248_0    conda-forge
scipy                     1.5.3            py38hb2138dd_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
sip                       6.5.1            py38h709712a_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
sqlparse                  0.4.4              pyhd8ed1ab_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.2            py38h01eb140_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
vsearch                   2.13.3               h76f5088_0    bioconda
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
werkzeug                  2.3.7              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

Thanks so much for your help!

~Nick

**Comment by didillysquat** [comment]
Hey Nick, I'm pinging @greenjune-ship-it who is now handling the maintenance of SymPortal.

**Comment by greenjune-ship-it** [comment]
Hi @Nicholas-Kron 

I see the following error:
`AttributeError: 'DataFrame' object has no attribute 'append'.
`
It happens due to incorrect conda environment resolution. The installed pandas version is not compatible with SymPortal.

May I ask you to try to restore the environment with the following `environment.yml`?

```
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.8.15=h257c98d_0_cpython
  - numpy=1.24.3=py38h59b608b_0
  - biopython=1.81=py38h1de0b5d_0
  - django=4.2.1=pyhd8ed1ab_0
  - matplotlib=3.6.3=py38h578d9bd_0
  - pandas=1.5.3=py38hdc8b05c_1
  - plumbum=1.8.1=pyhd8ed1ab_0
  - scipy=1.5.3=py38hb2138dd_0
  - scikit-bio=0.5.6=py38h0b5ebd8_4
  - openpyxl=3.1.2=py38h01eb140_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - blast=2.14.0=hf3cf87c_0
  - iqtree=2.2.2.3=hb97b32f_0
  - mafft=7.520=hec16e2b_0
  - mothur=1.43.0=hd76352b_0
  - psycopg2=2.9.3=py38h0ca591d_2
  - werkzeug=2.3.3=pyhd8ed1ab_0
  - textdistance=4.5.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
```

Please, let me know if it helps.

Best regards,
Yulia

**Comment by Nicholas-Kron** [comment]
Hi Yulia,

Thank you for the fix! This has fixed the error for both SQLite3 and PostgreSQL. I had to remove `'OPTIONS': {'timeout':200}` from the settings.py as well to get the PostgreSQL to work without error, but now everything is working just fine. Thank you for your help!

~Nick
