### ISSUE TITLE
Issue running "python3 -m tests.tests" to check installation

### ISSUE THREAD

**Issue by GenericUsername23094582** [didillysquat/SymPortal_framework#131]
Hi, 

I am trying to install and run symportal locally.  I didn't have any problems up until step 6 of SymPortal setup.  I apologize in advance if the answer to my issues is obvious, I am a relative beginner with python, coding, and analysis of genetic data in general.  I am hoping you can advise me how to proceed given the issues i'm having.  Thank you in advance.  

I ran python3 -m tests.tests and the program ran for a minute or two, but then gave the error:

AttributeError: 'DataFrame' object has no attribute 'append'

I will copy the larger context at the bottom of this post, but I think the error could have something to do with Dataframe.append.  From another github post: "DataFrame.append was deprecated in version 1.4 and removed from the pandas API entirely in version 2.0"

I also tried to proceed with running Symportal on two test samples despite the error.  It ran for quite a while (I have a huge amount of data, produced via lcWGS rather than Sanger seq of PCR product) but eventually failed.  I assume these two issues are likely connected?  Output from my attempted run:

./main.py --load [path/to/fastq/directory] --name first_loading --num_proc 5 --data_sheet [path/to/datasheet]
[path/]miniconda3/envs/symportal_env/lib/python3.8/site-packages/openpyxl/worksheet/_read_only.py:81: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():
Lat and long are currently nan for sample1. Values will be set to 999
Lat and long are currently nan for sample2. Values will be set to 999
 
Creating data_set_sample objects
Creating data_set_sample sample1
Creating data_set_sample sample2
 
Performing initial mothur QC
sample1: QC started
sample2: QC started
sample1: data_set_sample_instance_in_q.num_contigs = 9245499
sample1: starting fwd PCR. This may take some time.
sample2: data_set_sample_instance_in_q.num_contigs = 22990452
sample2: starting fwd PCR. This may take some time.
sample2: starting rev PCR. This may take some time.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "[my/path/to/conda/]miniconda3/envs/symportal_env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "[my/path/to/conda/]miniconda3/envs/symportal_env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "[my/path/to/conda/]new_tools/SymPortal_framework/data_loading.py", line 2030, in _worker_initial_mothur
    initial_morthur_worker.start_initial_mothur_worker()
  File "[my/path/to/conda/]new_tools/SymPortal_framework/data_loading.py", line 2064, in start_initial_mothur_worker
    self._do_fwd_and_rev_pcr()
  File "[my/path/to/conda/]new_tools/SymPortal_framework/data_loading.py", line 2112, in _do_fwd_and_rev_pcr
    self.mothur_analysis_object.execute_pcr(do_reverse_pcr_as_well=True)
  File "[my/path/to/conda/]new_tools/SymPortal_framework/symportal_utils.py", line 199, in execute_pcr
    if do_reverse_pcr_as_well and self._if_scrap_fasta_exists_clean_and_write_out(fwd_output_scrapped_fasta_path):
  File "[my/path/to/conda/]new_tools/SymPortal_framework/symportal_utils.py", line 288, in _if_scrap_fasta_exists_clean_and_write_out
    new_scrapped_fasta = self._make_new_fasta_no_multi_match_lines(scrapped_fasta_as_list)
  File "[my/path/to/conda/]new_tools/SymPortal_framework/symportal_utils.py", line 300, in _make_new_fasta_no_multi_match_lines
    if not 'multipleMatches' in scrapped_fasta_as_list[i] and len(scrapped_fasta_as_list[i + 1]) > 1:
IndexError: list index out of range
sample2: Error in processing sample

Finally, here is the larger context of the installation test, the last part of the output:

Creation of DataSetSampleSequencePM objects took 0.277554988861084s
SAMPLE PROCESSING SUMMARY
A01: Successful
A01_no_overlap: Error in processing: error in inital QC during screen seqs overlap
1234: Successful
A02: Successful
A03: Successful
A04: Successful
A05: Successful
A06: Successful
A07: Successful
A08: Successful
A09: Successful
A10: Successful
A11: Successful
A12: Successful
A13: Successful
C01: Successful
C02: Successful
C03: Successful
C04: Successful
C05: Successful
C06: Successful
C07: Successful
C08: Successful
C09: Successful
C10: Successful
C11: Successful
C12: Successful
C13: Successful
C14: Successful
C15: Successful
Y01: Successful
Y02: Successful
Y03: Successful
Y04: Successful
Y05: Successful
Y06: Successful
Y07: Successful
Y08: Successful
Y09: Successful
Y10: Successful
Y11: Successful
Y12: Successful
Y13: Successful
Y15: Successful
no_sym_0: Error in processing: No symbiodiniaceae sequences left in sample after pre-med QC
no_sym_1: Error in processing: No seqs left after PCR
 
 
43 out of 46 samples successfully passed QC.
3 samples produced errors
 
 
 
Backup of named reference_sequences output to [my/path/]SymPortal_framework/dbBackUp/seq_dumps/seq_dump_20231109T235201
 
 
Data loading complete. DataSet UID: 5; Name: testing
 
Generating count tables for post- and pre-MED sequence abundances
 
data_analysis.py  db.sqlite3         general.py     manage.py  pop_datasheet_seq_file_cols.py  reference_trees  sp_config.py       tests
 
Outputting sequence abundance count tables
 
no_sym_1: collecting seq abundancesdances
 
Outputting seq data
Outputting seq data for Y13: sequence 1355_CC
Generating ordered sample list and ordering dataframe accordingly
183: Getting maj seq for sample
Going clade by clade sorting by abundance
Populating the relative dataframe with series. This could take a while...
Generating accession and fasta
Appending accession info and creating fasta 1355_C: 84/85Traceback (most recent call last):5/8585
  File "[my/path/]miniconda3/envs/symportal_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "[my/path/]miniconda3/envs/symportal_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "[my/path/]SymPortal_framework/tests/tests.py", line 154, in <module>
    symportal_tester.execute_integrated_tests()
  File "[my/path/]SymPortal_framework/tests/tests.py", line 24, in execute_integrated_tests
    self._test_data_loading_work_flow()
  File "[my/path/]SymPortal_framework/tests/tests.py", line 32, in _test_data_loading_work_flow
    self.work_flow_manager.start_work_flow()
  File "[my/path/]SymPortal_framework/main.py", line 329, in start_work_flow
    self.perform_data_loading()
  File "[my/path/]SymPortal_framework/main.py", line 695, in perform_data_loading
    self._execute_data_loading()
  File "[my/path/]SymPortal_framework/main.py", line 722, in _execute_data_loading
    self.data_loading_object.load_data()
  File "[my/path/]SymPortal_framework/data_loading.py", line 214, in load_data
    self._output_seqs_count_table()
  File "[my/path/]SymPortal_framework/data_loading.py", line 364, in _output_seqs_count_table
    self.sequence_count_table_creator.make_seq_output_tables()
  File "[my/path/]SymPortal_framework/output.py", line 1096, in make_seq_output_tables
    self._make_output_tables_post_med()
  File "[my/path/]SymPortal_framework/output.py", line 1115, in _make_output_tables_post_med
    self._add_uids_for_seqs_to_dfs()
  File "[my/path/]SymPortal_framework/output.py", line 1502, in _add_uids_for_seqs_to_dfs
    self.output_df_absolute_post_med = self.output_df_absolute_post_med.append(temp_series)
  File "[my/path/]miniconda3/envs/symportal_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by greenjune-ship-it** [comment]
Hi @GenericUsername23094582 

Please, see the following issue that solves your problem #129.
I've updated the [environment file](https://github.com/didillysquat/SymPortal_framework/blob/master/symportal_env.yml), check it out.

P.S.: unfortunatelly we are not supporting the SymPortal local installation anymore, so if you are interested in SymPortal, please, file the onboarding request to the current maintaner (see details at [symportal.org](https://symportal.org/)).

Best regards,
Yulia

**Comment by GenericUsername23094582** [comment]
Hello Yulia,

Thank you for your reply!  The installation test now works.
