### ISSUE TITLE
handle tree rooting error from unifrac calculation

### ISSUE THREAD

**Issue by didillysquat** [didillysquat/SymPortal_framework#90]

**Comment by didillysquat** [comment]
The tree that is causing the error: (378:0.0085809758,435:0.0085809758,(58:1.3234e-06,(73:0.0042728154,(171:0.0042728154,61:1.3234e-06):0.004273):1e-06):1e-06)root;

This seems to be a perfectly valid tree so I'm not sure why were getting the error:

======================================================================
ERROR: test_stand_alone_unifrac_type_distances_data_set_sample_uid_input (tests.django_tests.SPIntegrativeTestingJSONOnly)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/tests/django_tests.py", line 118, in test_stand_alone_unifrac_type_distances_data_set_sample_uid_input
    test_spwfm.start_work_flow()
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/main.py", line 237, in start_work_flow
    self.perform_type_distance_stand_alone()
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/main.py", line 635, in perform_type_distance_stand_alone
    self.run_type_distances_dependent_on_methods()
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/main.py", line 647, in run_type_distances_dependent_on_methods
    self._start_type_unifrac_data_set_samples()
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/main.py", line 730, in _start_type_unifrac_data_set_samples
    self.distance_object.compute_unifrac_dists_and_pcoa_coords()
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/distance.py", line 230, in compute_unifrac_dists_and_pcoa_coords
    wu = self._perform_unifrac(clade_abund_df, tree)
  File "/Users/humebc/Documents/symportal_testing/SymPortal_framework/distance.py", line 351, in _perform_unifrac
    tree=tree, otu_ids=[str(_) for _ in list(clade_abund_df.columns)])
  File "/Users/humebc/phylogenetic_software/miniconda3/envs/symportal_python/lib/python3.6/site-packages/skbio/diversity/_driver.py", line 365, in beta_diversity
    validate=validate)
  File "/Users/humebc/phylogenetic_software/miniconda3/envs/symportal_python/lib/python3.6/site-packages/skbio/diversity/beta/_unifrac.py", line 521, in _setup_multiple_weighted_unifrac
    _setup_multiple_unifrac(counts, otu_ids, tree, validate)
  File "/Users/humebc/phylogenetic_software/miniconda3/envs/symportal_python/lib/python3.6/site-packages/skbio/diversity/beta/_unifrac.py", line 449, in _setup_multiple_unifrac
    _validate_otu_ids_and_tree(counts[0], otu_ids, tree)
  File "/Users/humebc/phylogenetic_software/miniconda3/envs/symportal_python/lib/python3.6/site-packages/skbio/diversity/_util.py", line 79, in _validate_otu_ids_and_tree
    raise ValueError("``tree`` must be rooted.")
ValueError: ``tree`` must be rooted.

----------------------------------------------------------------------

**Comment by didillysquat** [comment]
As a temporary fix to maintain stability I will catch the error and skip distance generation for the clade in question. commit to come.

**Comment by didillysquat** [comment]
I'm closing this for the time being as I can't figure out what is causing the issue.
